# Generated by Django 2.2.7 on 2019-11-30 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kioskoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinero', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('pase_anual', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp', models.IntegerField(default=1)),
                ('perfil', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='kioskoapp.Perfil')),
            ],
        ),
        migrations.DeleteModel(
            name='UserDjango',
        ),
    ]
